### ISSUE TITLE
Ninja Form Failure to Submit 

### ISSUE THREAD

**Issue by maclee31** [zaus/forms-3rdparty-integration#100]
We are using Ninja Forms with the Forms 3rdParty Integration plugin. No matter what we try, the form will not submit when the plugin is active. We always get a "Too many redirects" error. 

Here is the full Debug report. Any assistance with be great! Thanks!

`*** Service ***
Array
(
    [name] => Pardot
    [url] => http://go.pardot.com/XXXXXXX
    [forms] => Array
        (
            [0] => njn_113
        )

    [success] =>
    [failure] =>
    [timeout] => 45
    [mapping] => Array
        (
            [0] => Array
                (
                    [lbl] => email
                    [src] => 554
                    [3rd] => Email (r)
                )

            [1] => Array
                (
                    [lbl] => first name
                    [src] => 550
                    [3rd] => First Name
                )

            [2] => Array
                (
                    [lbl] => Last Name
                    [src] => 553
                    [3rd] => Last Name
                )

        )

)

*** Post (Form) ***
http://www.XXXXX.com/pardot-form-test/
Array
(
    [570] =>
    [554] => test@test.com
    [551] =>
    [552] =>  *
    [550] => Test
    [553] => Test
    [569] =>
    [IP Address] =>
    [Email] => test@test.com
    [User IP] =>
    [] =>  *
    [First Name] => Test
    [Last Name] => Test
    [Submit] =>
)

*** Post (to Service) ***
Array
(
    [timeout] => 45
    [body] => Array
        (
            [Email (r)] => test@test.com
            [First Name] => Test
            [Last Name] => Test
        )

)

*** Response ***
WP_Error Object
(
    [errors] => Array
        (
            [http_request_failed] => Array
                (
                    [0] => Too many redirects
                )

        )

    [error_data] => Array
        (
        )

)

`

**Comment by zaus** [comment]
I think that's a Pardot issue rather than Ninja Forms -- lots and lots of forum posts about this and they're always about Pardot even if they're GF or CF7 instead.
