### ISSUE TITLE
Integrations Deleting Themselves?

### ISSUE THREAD

**Issue by kzr2101** [zaus/forms-3rdparty-integration#101]
I'm using this plugin with Gravity Form submissions. Every time I add a new one, the bottom-most listed integration gets emptied. Has anyone else experienced this before?

**Comment by zaus** [comment]
How many services do you have?  There is a physical memory limit (because my plugin saves everything to a single setting, eventually in v2 they'll be custom post types like they should) so if you have too many mappings and too many services they get arbitrarily chopped off.
