### ISSUE TITLE
Not Integrating with Salesforce

### ISSUE THREAD

**Issue by Rondeau-CMM** [zaus/forms-3rdparty-integration#105]
I know I created an issue earlier, but this time I've come back a little wiser. I've worked with my web host (pair.com) and Salesforce to test everything else this issue could possibly be caused by.

-  Several tests from several locations suggest that TLS 1.0, 1.1 and 1.2 are all enabled on my website/server.
-  I've tested Salesforce's native Web-To-Lead form on my website and it successfully communicated with Salesforce.
- I've increased the Request Timeout to 300 to see if the connection severing early was an issue on my end or Salesforce. The wheel under the Contact Form 7 seems to spin for about 10 seconds before suggesting a successful submission.

So to me, the only possible answer is this particular plug-in or another component I've installed on my WP instance is creating an issue.

Again, the error I'm receiving is:

`(
    [safe_message] => error object
    [object] => WP_Error Object
        (
            [errors] => Array
                (
                    [http_request_failed] => Array
                        (
                            [0] => cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
                        )

                )

            [error_data] => Array
                (
                )

        )

)`

Please help. I'm desperate for answers at this point. Additionally, I've reached out to folks on SF forums.

**Comment by zaus** [comment]
Some googling:

* https://stackoverflow.com/questions/3876563/curl-request-is-failing-on-the-ssl
* https://github.com/stevenmaguire/trello-php/issues/24

How big is your submission?  Can you turn on wp_debug mode?  Maybe there will be more info in the debug log?

**Comment by Rondeau-CMM** [comment]
Feel free to mark this as 'Closed' - In their recent update, Salesforce changed the Submission URL. Despite my speaking with them, this was not something they thought to mention as a potential solution. Thanks so much for your efforts and time!

**Comment by zaus** [comment]
Hahaha, sorry, I got a good chuckle out of that, mostly from relief; glad it was something easy to "fix".  I'm surprised they weren't more vocal to subscribers about such a breaking change.
