### ISSUE TITLE
Multiple Fields within one

### ISSUE THREAD

**Issue by ianferrell** [zaus/forms-3rdparty-integration#106]
I'm using Contact Form 7.

Say I want to take two fields from my contact form and combine them to be sent as one over to my webhook. How could I accomplish this?

Currently it's being sent as:
`firstname=field1&lastname=field2&msg=test`

Is there a filter I can use to do something like:
`name=field1+field2&msg=test`

Thank you for your awesome work.

**Comment by zaus** [comment]
Just map them both to the same 3rdparty field name.  You can specify the separator to something other than a comma.

https://github.com/zaus/forms-3rdparty-integration/blob/master/README.md#i-need-to-submit-multiple-values-as
