### ISSUE TITLE
Unable to select 'Add Another Service' if all others have been deleted.

### ISSUE THREAD

**Issue by jburcsik** [zaus/forms-3rdparty-integration#29]
I removed all of the services so that there are none. When I click on 'Add Another Service' an error is thrown and the new service dialogue is not displayed.

![image](https://cloud.githubusercontent.com/assets/1092839/5001411/62c2c868-69c3-11e4-8e08-2285f6be29ae.png)

**Comment by zaus** [comment]
Probably resolved?
