### ISSUE TITLE
Phone Number Is In The Wrong Format

### ISSUE THREAD

**Issue by mauree** [zaus/forms-3rdparty-integration#33]
I am getting an error response

 [body] => Phone Number Is In The Wrong Format
    [response] => Array

should this be sanitized using add_filter? if so how would I do that?

**Comment by zaus** [comment]
This is the response from your 3rdparty service, not the plugin, right?

In which case, you can hook to `..._service_filter_args` ([see source](https://github.com/zaus/forms-3rdparty-integration/blob/master/forms-3rdparty-integration.php#L478)), look for the phone-number field in `$args['body']['your-phone-field']`, and manipulate it as needed.  Or enforce some kind of formatting before submission (I think Gravity and Ninja Forms have this kind of validation, or use custom javascript).
