### ISSUE TITLE
CF7 4.1.2 & 3rdParty 1.6.4.2 & SalesForce > retURL not working

### ISSUE THREAD

**Issue by systatsoftware** [zaus/forms-3rdparty-integration#39]
Dear Zaus,

Love this plugin, I can get it to make a SFA opportunity with all the fields however, the form just tells me success and never moves to the page entered in retURL.

https://systatsoftware.com/download-sigmaplot/

Here is error log and integration debug:

There was an error when trying to integrate with the 3rd party service {Download SigmaPlot} (https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8).

**FORM**
Title: Download SigmaPlot
Intended Recipient: mta@systatsoftware.com
Source: https://systatsoftware.com/download-sigmaplot/

**SUBMISSION**
Array
(
    [timeout] => 10
    [body] => Array
        (
            [first_name] => Greg TEST
            [last_name] => Greg TEST
            [company] => Greg TEST
            [email] => greg@test.com
            [industry] => Manufacturing
            [city] => San Jose
            [state] => CA
            [country] => USA (United States of America)
            [oid] => 00D600000007CiD
            [lead_source] => sigmaplot download
            [retURL] => https://systatsoftware.com/?p=253
            [recordType] => 01260000000DMcC
            [submit] => submit
        )

)

**RAW RESPONSE**
Array
(
    [reason] => Could not locate success clause within response
    [safe_message] => Success Clause not found
    [clause] => Thanks for choosing SigmaPlot!
    [response] =>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"> <html> <head> <meta HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE"> <meta http-equiv="Refresh" content="0; URL=https://systatsoftware.com/?p=253">
</head>
<script>if (this.SfdcApp && this.SfdcApp.projectOneNavigator) { SfdcApp.projectOneNavigator.handleRedirect('https://systatsoftware.com/?p=253'); }  else if (window.location.replace){ window.location.replace('https://systatsoftware.com/?p=253');} else {;window.location.href ='https://systatsoftware.com/?p=253';} </script></html>

)

*** Service ***
Array
(
    [name] => Download SigmaPlot
    [url] => https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8
    [forms] => Array
        (
            [0] => cf7_252
        )

    [success] => Thanks for choosing SigmaPlot!
    [failure] => 
    [timeout] => 10
    [mapping] => Array
        (
            [0] => Array
                (
                    [lbl] => first name
                    [src] => first_name
                    [3rd] => first_name
                )

            [1] => Array
                (
                    [lbl] => last name
                    [src] => last_name
                    [3rd] => last_name
                )

            [2] => Array
                (
                    [lbl] => company
                    [src] => company
                    [3rd] => company
                )

            [3] => Array
                (
                    [lbl] => email
                    [src] => your-email
                    [3rd] => email
                )

            [4] => Array
                (
                    [lbl] => industry
                    [src] => industry
                    [3rd] => industry
                )

            [5] => Array
                (
                    [lbl] => title
                    [src] => title
                    [3rd] => title
                )

            [6] => Array
                (
                    [lbl] => city
                    [src] => city
                    [3rd] => city
                )

            [7] => Array
                (
                    [lbl] => state
                    [src] => state
                    [3rd] => state
                )

            [8] => Array
                (
                    [lbl] => country
                    [src] => country
                    [3rd] => country
                )

            [9] => Array
                (
                    [lbl] => systat user
                    [src] => user
                    [3rd] => user
                )

            [10] => Array
                (
                    [lbl] => which products
                    [src] => 00N60000001JZ3l
                    [3rd] => 00N60000001JZ3l
                )

            [11] => Array
                (
                    [val] => 1
                    [lbl] => SFA ID
                    [src] => 00D600000007CiD
                    [3rd] => oid
                )

            [12] => Array
                (
                    [val] => 1
                    [lbl] => lead source
                    [src] => sigmaplot download
                    [3rd] => lead_source
                )

            [13] => Array
                (
                    [val] => 1
                    [lbl] => redirect
                    [src] => https://systatsoftware.com/?p=253
                    [3rd] => retURL
                )

            [14] => Array
                (
                    [val] => 1
                    [lbl] => SFA Record Type
                    [src] => 01260000000DMcC
                    [3rd] => recordType
                )

            [15] => Array
                (
                    [val] => 1
                    [lbl] => submit
                    [src] => submit
                    [3rd] => submit
                )

        )

    [separator] => ,
)

*** Post (Form) ***
https://systatsoftware.com/download-sigmaplot/
Array
(
    [_wpcf7] => 252
    [_wpcf7_version] => 4.1.2
    [_wpcf7_locale] => en_US
    [_wpcf7_unit_tag] => wpcf7-f252-p151-o1
    [_wpnonce] => 23013d3d64
    [first_name] => Greg TEST
    [last_name] => Greg TEST
    [company] => Greg TEST
    [your-email] => greg@test.com
    [tel-380] => 0123456789
    [industry] => Manufacturing
    [TitleorJobDescription] => Greg TEST
    [city] => San Jose
    [state] => CA
    [country] => USA (United States of America)
    [SystatUser] => Array
        (
            [0] => No
        )

    [_wpcf7_is_ajax_call] => 1
    [product] => Array
        (
            [0] => 
        )

)

*** Post (to Service) ***
Array
(
    [timeout] => 10
    [body] => Array
        (
            [first_name] => Greg TEST
            [last_name] => Greg TEST
            [company] => Greg TEST
            [email] => greg@test.com
            [industry] => Manufacturing
            [city] => San Jose
            [state] => CA
            [country] => USA (United States of America)
            [oid] => 00D600000007CiD
            [lead_source] => sigmaplot download
            [retURL] => https://systatsoftware.com/?p=253
            [recordType] => 01260000000DMcC
            [submit] => submit
        )

)

*** Response ***
Array
(
    [headers] => Array
        (
            [date] => Thu, 07 May 2015 20:41:56 GMT
            [set-cookie] => BrowserId=YTp1YiceRkeWYla03-JAOA;Path=/;Domain=.salesforce.com;Expires=Mon, 06-Jul-2015 20:41:56 GMT
            [expires] => Thu, 01 Jan 1970 00:00:00 GMT
            [cache-control] => private,s-maxage=0
            [content-type] => text/html;charset=UTF-8
            [content-encoding] => gzip
            [connection] => close
        )

    [body] =>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"> <html> <head> <meta HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE"> <meta http-equiv="Refresh" content="0; URL=https://systatsoftware.com/?p=253">
</head>
<script>if (this.SfdcApp && this.SfdcApp.projectOneNavigator) { SfdcApp.projectOneNavigator.handleRedirect('https://systatsoftware.com/?p=253'); }  else if (window.location.replace){ window.location.replace('https://systatsoftware.com/?p=253');} else {;window.location.href ='https://systatsoftware.com/?p=253';} </script></html>

    [response] => Array
        (
            [code] => 200
            [message] => OK
        )

    [cookies] => Array
        (
            [0] => WP_Http_Cookie Object
                (
                    [name] => BrowserId
                    [value] => YTp1YiceRkeWYla03-JAOA
                    [expires] => 1436215316
                    [path] => /
                    [domain] => .salesforce.com
                )

        )

    [filename] =>
)

I've Googled everywhere and I can't seem to get it to work.
Thanks for your help and this awesome plugin!

**Comment by systatsoftware** [comment]
Still need help with this. Anyone??

**Comment by systatsoftware** [comment]
I failed to mention that we're developing on a new server at a different domain. The problem is SF doesn't have a means to test Web2Lead without changing the domain name. Case closed, for now.

**Comment by zaus** [comment]
Sorry that I didn't have a chance to answer your question.  The reason the 3rdparty response doesn't automatically redirect is because it's performing the post programmatically rather than navigating the browser to that page (like a regular form post would).  You have to use a hook to modify the `$form` result or otherwise manually perform the redirect via `wp_redirect` or something similar.  There have been a couple forum/ticket posts regarding this, I'll follow up on those for you.

I'd also recommend setting the "Success Clause" to something that's only present in a successful raw response, like `http-equiv="Refresh"`.  I think you're assuming it's the text that's shown on success; as an aside, the main point of this plugin is a "silent" post that's secondary to the regular form plugin (i.e. Gravity Forms or Contact Form 7).

**Comment by zaus** [comment]
Some forum posts regarding redirect
* https://wordpress.org/support/topic/forms3rdpartyintegration_service-cf7-ajax?replies=3
* https://github.com/zaus/forms-3rdparty-integration/issues/10 -- this seems to be a different redirect requirement, instead
