### ISSUE TITLE
CF7 to sugarCRM

### ISSUE THREAD

**Issue by pbrochier** [zaus/forms-3rdparty-integration#41]
Hello
I am trying to connect a contact-form-7 to a webtolead form in sugarcrm.
I installed your plugin and started to enter a service.
Only two fields are intentified for mapping but there are around 40 of them.
What do I have to do to be able to map them all . it also looks like the connection to sugar is not done.
Here is what I get in debug mode
thanks for your help

http://www.incontinuum.com/marketing/request-a-freemium-key/

*** Service ***
Array
(
    [name] => Service Freemium License
    [url] => https://incontinuum.synolia.com/index.php?entryPoint=WebToLeadCapture
    [forms] => Array
        (
            [0] => cf7_12773
        )

    [success] => 
    [failure] => 
    [timeout] => 10
    [mapping] => Array
        (
            [0] => Array
                (
                    [lbl] => The submitter name
                    [src] => your-name
                    [3rd] => name
                )

            [1] => Array
                (
                    [lbl] => The email address
                    [src] => your-email
                    [3rd] => email
                )

        )

    [separator] => , 
)

*** Post (Form) ***
http://www.incontinuum.com/marketing/request-a-freemium-key/
Array
(
    [_wpcf7] => 12773
    [_wpcf7_version] => 4.1.2
    [_wpcf7_locale] => en_US
    [_wpcf7_unit_tag] => wpcf7-f12773-p12774-o1
    [_wpnonce] => 41b7c694d3
    [courtesy] => Mr.
    [firstname] => a
    [your-name] => z
    [your-email] => p.....@gmail.com
    [phone] => +336...........
    [function] => 
    [country] => USA
    [state] => Non-US
    [company] => a
    [address] => z
    [address2] => e
    [address3] => r
    [zipcode] => t
    [city] => y
    [industry] => Education
    [orgatype] => Enterprise
    [cloudbuilt] => Private Cloud
    [eula] => 1
    [renewal] => Array
        (
            [0] => First Demand
        )

    [hypervisors] => Array
        (
            [0] => VMware vCenter
        )

    [publicused] => Array
        (
            [0] => Amazon Web Services
        )

    [startingdate] => 2015-05-31
    [source] => IBM Marketplace
    [your-message] => gfgt
    [_wpcf7_is_ajax_call] => 1
)

*** Post (to Service) ***
Array
(
    [timeout] => 10
    [body] => Array
        (
            [name] => z
            [email] => pa.......@gmail.com
        )

)

*** Response ***
Array
(
    [headers] => Array
        (
            [date] => Fri, 22 May 2015 15:45:23 GMT
            [server] => Apache
            [content-encoding] => gzip
            [vary] => Accept-Encoding
            [content-length] => 83
            [connection] => close
            [content-type] => text/html; charset=UTF-8
        )

    [body] => We are sorry, the server is currently unavailable, please try again later.
    [response] => Array
        (
            [code] => 200
            [message] => OK
        )

    [cookies] => Array
        (
        )

    [filename] => 
)

**Comment by zaus** [comment]
You need to map all of the fields sugarCRM wants to see.

Closing -- not an issue with the plugin.
