### ISSUE TITLE
Escaping single quotes

### ISSUE THREAD

**Issue by JimMichels** [zaus/forms-3rdparty-integration#42]
The data is passed to Sales Force. Single quotes like in "L'espoir" are posted like "L\'espoir".

Thanks in advance

**Comment by AMeidl** [comment]
I am having the same issue and need to be able to pass a value to Salesforce that has a single quote in the value.  "Bachelor's"  needs to be passed but "Bachelor\'s" is being passed  instead.  Is there a workaround for this?

**Comment by zaus** [comment]
Unfortunately it's a "feature" of Wordpress that they escape slashes; are you using Gravity Forms, by chance?  It probably doesn't matter, but GF provides the form submission directly from the `$_POST` array, which WP escapes.

As I hastily mentioned on the [support forum thread](https://wordpress.org/support/topic/dont-escape-single-quotes-when-posting-to-third-party-service), you should be able to apply a late filter to [`...service_filter_post`](https://github.com/zaus/forms-3rdparty-integration/blob/master/forms-3rdparty-integration.php#L462) or even to [`...get_submission`](https://github.com/zaus/forms-3rdparty-integration/blob/master/forms-3rdparty-integration.php#L420) and call [`stripslashes_deep`](https://codex.wordpress.org/Function_Reference/stripslashes_deep) on the post array.  Something like:

    add_filter('Forms3rdPartyIntegration_get_submission', 'fix_3rdparty_slashes', 20, 2);
    function fix_3rdparty_slashes($post, $form) {
        return stripslashes_deep($post);
    }

**Comment by AMeidl** [comment]
Thank you very much!  This solved the problem perfectly!

**Comment by JulesBern** [comment]
@AMeidl can you post exactly how you got this to work?

**Comment by AMeidl** [comment]
I used the exact code supplied in Zaus post above and put it in my functions.php in my themes folder.

**Comment by AMeidl** [comment]
I should probably mention we are using Gravity Forms so the $_post array part is compatible with our needs.

**Comment by zaus** [comment]
So...I think it made sense to just [fix it directly](https://github.com/zaus/forms-3rdparty-integration/blob/master/plugins/gravityforms.php#L77) -- anyone want to try the [plugin from GitHub](https://github.com/zaus/forms-3rdparty-integration/archive/master.zip) and let me know if that fixes the issue, but doesn't break GF submissions in general?  If it's good I can push the change to Wordpress too.

**Comment by JulesBern** [comment]
@zaus I just tested it and can confirm that the fix from GitHub works.
Thank you!

**Comment by zaus** [comment]
Sorry, I had forgotten to commit the changes to SVN as well as GitHub.  Now live as v1.6.4.3.
