### ISSUE TITLE
Redirect to payment gateway not working using CF7 + 3rd

### ISSUE THREAD

**Issue by shirani182** [zaus/forms-3rdparty-integration#45]
I'm trying to get the post action to actually redirect the client to a payment gateway once they click submit on my form.
I configured some hidden field on the CF7 and mapped filed using the 3rd party plugin, and i need these field values to be posted to the payment URL so the payment page successfully works.

I turned on the debug mode and I don't get any error in response (attached bellow).
And despite this it is not redirect the page to the url set in "submission url"

Do I need to add hook? witch on? 

Thanks Shiran.

*** Service ***
Array
(
    [name] => Tranzila
    [url] => https://direct.tranzila.com/ttxbpracti/
    [forms] => Array
        (
            [0] => cf7_13181
        )

    [success] =>
    [failure] =>
    [timeout] => 10
    [mapping] => Array
        (
            [0] => Array
                (
                    [lbl] =>
                    [src] => your-name
                    [3rd] => contact
                )

            [1] => Array
                (
                    [lbl] =>
                    [src] => your-email
                    [3rd] => email
                )

            [2] => Array
                (
                    [lbl] =>
                    [src] => your-subject
                    [3rd] => phone
                )

        )

    [separator] => ,
)

*** Post (Form) ***
http://www.bpracti.co.il/?page_id=12946&preview=true&preview_id=12946&preview_nonce=592cd3e314
Array
(
    [_wpcf7] => 13181
    [_wpcf7_version] => 4.2.1
    [_wpcf7_locale] => he_IL
    [_wpcf7_unit_tag] => wpcf7-f13181-p12946-o1
    [_wpnonce] => da77a495e4
    [your-name] => sss
    [your-subject] => sss
    [your-email] => sss@ss.com
    [TranzilaToken] => some=value&andother=fdds
    [sum] => 15
    [_wpcf7_is_ajax_call] => 1
)

*** Post (to Service) ***
Array
(
    [timeout] => 10
    [body] => Array
        (
            [contact] => sss
            [email] => sss@ss.com
            [phone] => sss
        )

)

*** Response ***
Array
(
    [headers] => Array
        (
            [date] => Tue, 28 Jul 2015 16:52:07 GMT
            [server] => Apache
            [x-xss-protection] => 0
            [p3p] => CP="HONK IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
            [set-cookie] => PHPSESSID=muk15j6pephbnh4ghukv326237; path=/; domain=direct.tranzila.com; secure
            [expires] => Thu, 19 Nov 1981 08:52:00 GMT
            [cache-control] => no-store, no-cache, must-revalidate, post-check=0, pre-check=0
            [pragma] => no-cache
            [vary] => Accept-Encoding
            [content-encoding] => gzip
            [content-length] => 5129
            [connection] => close
            [content-type] => text/html; charset=UTF-8
        )

    [body] => <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>Bpracti סדנאות פרקטיקה - טרנזילה שירותי סליקה באינטרנט</title><meta name="description" content="Bpracti סדנאות פרקטיקה - דף תשלומים באמצעות טרנזילה שירותי סליקה באינטרנט" /><meta name="keywords" content="סליקה, סליקת כרטיסי אשראי , סליקה באינטרנט , בילינג , גביה , גבייה , הוראת קבע , חתימה דגיטלית , כרטיסי אשראי , חיוב , ש.ב.א , מסוף סליקה , כרטיס אשראי , אשראי , מסוף אשראי , פייפאל , פייפל , סחר אלקטרוני ,אייפון, סליקה ניידת, iPhone, סליקה באמצעות אייפון, סליקה באמצעות מחשב נייד, תשלום , תשלומים , כרטיסי אשראי , אבטחת מידע , מפתח הצפנה , מסחר אלקטרוני, הוראות קבע , xkhev , סליקת אשראי , paypal, visa, mastercard , isracard , secure card , billing ,online payment , internet payment , SSL , credit card processing" /><style type="text/css">

                                body {padding: 0px; margin: 0px; direction: rtl; font-family: Arial;}

                        .rounded_corners { -moz-border-radius:6px 6px 6px 6px; -webkit-border-radius:6px 6px 6px 6px; border-radius: 6px 6px 6px 6px; }

                        #wrapper { width: 987px; margin: 0px auto;}

                        #header { width: 987px; margin: 0 auto;}

                        #contentp { width: 703px; margin: 0 auto; float: left;}

                        #details { width: 222px; margin: 0 auto; float: right;}

                        #gray { width: 62px; margin: 0 auto; float: right;}

                        #footer { width: 987px; margin: 20px auto;}

                        .content { width: 495px;  list-style-type: none; float: left;}

                        .product { width: 208px; margin: 15px auto; float:right;}

                        img {border: 0;}

                        .headimages { width: 987px; list-style-type: none;}

                        .headimages li { display: block; float: right;}

                        #greenstripe {width: 987px; height:53px; background-color:#33a2fe; list-style-type: none; margin: 0 auto; padding: 0;}

                        .orangestripe {width: 700px; height:28px; background-color:#000e77; margin: 3px auto; padding: 0;}

                        #greenstripe  li{display: block; float: left; padding: 30px 50px 0 60px;}

                        #details ul {list-style-type: none; width: 100%; padding: 0; margin: 0;}

                        .footerlink {font-size: 12px; font-weight: normal; text-decoration: underline; color:#888; cursor: pointer;}

                        #footergreenstripe {width: 987px; height:27px; background-color:#33a2fe; margin: 5px 0 10px 0; padding: 0;}

                        .footergreenstripe ul {list-style-type: none; width: 100%; padding: 0; margin: 0;}

                        .footergreenstripe  li{display: block; float: right; padding: 0 0 20px 20px; list-style-type: none;}

                        .text {font-style: Arial; color:#6e6e6e; font-weight: normal; font-size:12px; direction: rtl;}

                        .text ul{list-style-type: circle; padding: 0; margin: 0;}

                        .text li{float: right; display: block; font-weight: normal;  padding: 0; margin: 0;}

                        .content ul{list-style-type: none; width: 100%;  padding: 0; margin: 0; }

                        .content li{float: right; display: block;  padding: 0; margin: 0;}

                        .date {font-style: Arial; color:#ffffff; font-weight: bold; font-size:12px;}

                        .footertranzila{font-style: Arial; color:#649c0a; font-weight: bold; font-size:14px;}

                        .footertext{font-style: Arial; color:#666666; font-weight: bold; font-size:12px;}

                        .footertext a:link {font-size: 12px; font-weight: normal; text-decoration: underline; color: #888888; }

                        .footertext a:visited {font-size: 12px; font-weight: normal; text-decoration: none; color:#888888; }

                        .footertext a:active {font-size: 12px; font-weight: normal; text-decoration: none; color:#888888; }

                        .footertext a:hover {font-size: 12px; font-weight: normal; text-decoration: none; color:#649c0a;}

                        .productname {font-style: Arial; color:#000e77; font-weight: bold; font-size:16;}

                        .bizname {font-style: Arial; color:#000e77; font-weight: bold; font-size:16; padding-right: 5px;}

                        .price {font-style: Arial; color:#000000; font-weight: bold; font-size:18px; height: 10px;}

                        .strike {font-style: Arial; color:#fd4403; font-weight: bold; font-size:18px; text-decoration: line-through; height: 10px;}

                        .biztext {font-style: Arial; color:#6e6e6e; font-weight: normal; font-size:12px; direction: rtl; padding-right: 5px; margin:2px;}

                        .biztext a:link {font-size: 12px; font-weight: normal; text-decoration: underline; color: #33a2fe; }

                        .biztext a:visited {font-size: 12px; font-weight: normal; text-decoration: none; color:#649c0a; }

                        .biztext a:active {font-size: 12px; font-weight: normal; text-decoration: none; color:#649c0a; }

                        .biztext a:hover {font-size: 12px; font-weight: normal; text-decoration: none; color:#649c0a;}

                        .pf {display: block; float: left; width: 142px; height: 91px; background: url('/images/paymentform-blue.png') no-repeat left; margin-top: 10px;}

                        .photo {display: block; width: 142px; height: 91px; padding: 0 25px 0 0;}

                        .checkoutb { color:#0066CC; font-size: 14px; padding: 20px; margin: 0; text-align: left; width: 86%; }

                        .checkoutb img {vertical-align:middle}

                        .logom {width: 219px; height:154px; background-color:#ffffff; margin: 3px auto; padding: 0; float: center;}

                        .graystripe {width: 61px; height:28px; background-color:#d7d7d7; margin: 3px auto; padding: 0; float: right;}

                        .logotext {padding: 20px 0 60px 0;}

                        .orangeright {margin: 30px 0 60px 0; background: url('/images/blue-right.png') no-repeat right; width: 363px; height: 104px;}

                        .geo {padding: 30px 0 10px 0;}

                        form {font:13px Arial; margin:0px auto; width:495px;}

                        form ul {display: block; list-style:none; margin:0; padding:0;  }

                        form li { padding:56px; margin-bottom:1px;}

                        form label { float:right; width:70px; text-align:right; margin-right:7px; color:#0066CC; line-height:23px; padding:3px;}

                        form input, form textarea, form select { padding:4px; font:13px Arial; border:1px solid #999999; width:128px; }

                        form input:focus, form textarea:focus { border:1px solid #666; background:#e3f1f1; }

                        form li#send {  background:none; margin-top:6px; margin-right: 160px; text-align: left; color:#0066CC; font-size: 14px;}

                        form li#send button {   background:#33a1fe; border:none; margin:10px 25px 0 0; padding:8px 18px; text-align: center; border-radius:5%; -moz-border-radius:5%;-webkit-border-radius:5%;  color:#fff; margin-left:0; cursor:pointer; }

                        form li#send button:hover { background-color:#035eab;}

                        #send { background:#33a1fe; border:none; margin:10px 25px 0 0; padding:8px 18px; text-align: center; border-radius:5%; -moz-border-radius:5%;-webkit-border-radius:5%;  color:#fff; margin-left:0; cursor:pointer; }

                        .sexybluebutton {background:#33a1fe; border:none;  padding:8px 18px; text-align: center; border-radius:5%; -moz-border-radius:5%;-webkit-border-radius:5%;      color:#fff; margin-left:0; cursor:pointer;}

                        .sexybluebutton:hover { background-color:#035eab;}

.checkoutb { color:#0066CC; font-size: 14px; padding: 20px; text-align: left;  }

                        .checkoutb img {vertical-align:middle}

                         .ast { color: red; font-size: small;}

                        .checkoutb button {     background:#33a1fe; border:none; margin:0px 25px 0 0; padding:8px 18px; text-align: center; border-radius:5%; -moz-border-radius:5%;-webkit-border-radius:5%;   co

lor:#fff; margin-left:0; cursor:pointer; }

                        .checkoutb button:hover { background-color:#035eab;}

                        #returnMessage1 {background-color: #c60000; color: #ffffff; font-size: 18px; font-weight: bold; height: 30px; border: 1px solid black; width: 360px; margin: 5px; display: block; float: right; text-align: center; padding-top:14px; }

/*blue*/

                        .mysum {font-weight: bold; color:#7cb829; font-size: 15px;}

                        .mysumval{ color:#0066d3; font-weight: bold; font-size: 15px;}

                </style><script type="text/javascript">

  var _gaq = _gaq || [];

  _gaq.push(['_setAccount', 'UA-64776703-1']);

  _gaq.push(['_trackPageview']);

  (function() {

    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

  })();

</script><script src="/js/pay.js" type="text/javascript"></script><script type="text/javascript">

function trainto(URL)

{

     window.open(URL, '_blank', 'toolbar=0,scrollbars=1,location=0,statusbar=0,menubar=0,resizable=1,width=800,height=600');

}

</script></head><body>

                <div id="wrapper">

                        <div id="header">

                                <div>

                                <ul class="headimages"><li style="width: 510px;">  </li>

                                        <li style="padding: 15px 340px 10px 0px;">

                                        <a target="_blank" href="https://www.mcafeesecure.com/RatingVerify?ref=direct.tranzila.com" rel="nofollow"><img width="94" height="54" border="0" src="//images.scanalert.com/meter/direct.tranzila.com/13.gif" alt="McAfee SECURE site" /></a>

                                        </li>

                                </ul></div>

                <div style="clear: both"></div>

                                <ul id="greenstripe"><li class="date">

                        <span id="lang_bartitle">המערכת עומדת בתקן אבטחה PCI-DSS מוגנת בתקשורת מאובטחת ומוצפנת SSL</span>

                    </li>

                                </ul></div>

                        <div id="contentp">

                                <div class="orangestripe"> </div>

                                <div class="content">

                                        <p class="productname" id="item_nameView"></p>

                                                <ul><li class="price" id="priceView">סה"כ  ₪</li>

                                                        <li class="strike" style="padding-right: 10px;" id="oldprice"></li>

                                                </ul><br /><div class="text" style="padding: 15px 0px 10px 50px;" id="pdescView">

                                        <br /><br /></div>

<form action="/process/" class="round" method="post" id="tranpayform" autocomplete="off">

        <p class="checkoutb" style="margin-left: 50px;"> <span id="lang_paypal">Checkout with PayPal</span> -  <img style="cursor: pointer;" src="/images/btn_xpressCheckout.png" alt="CheckOut with PayPal Tranzila" onclick="ppsubmit();" /></p>

        <input type="hidden" name="pdesc" id="pdesc" value="" /><input type="hidden" id="lang" name="lang" value="il" /><ul><li>

                    <label for="contact"><span id="lang_contact">שם מלא</span><span class="ast">*</span></label>

                    <input style="width:273px;" type="text" name="contact" id="contact" value="sss" /></li>

        <li>

                    <label for="email"><span id="lang_email">דוא"ל</span><span class="ast">*</span></label>

                    <input type="text" name="email" id="email" value="sss@ss.com" /></li>

        <li>

                    <label for="phone"><span id="lang_phone">טלפון</span><span class="ast">*</span></label>

                    <input type="text" name="phone" id="phone" value="sss" /></li>

        <li>

                    <label for="address"><span id="lang_address">כתובת</span></label>

                    <input style="width:273px;" type="text" name="address" id="address" /></li>

        <li>

                    <label for="remarks"><span id="lang_remarks">הערות</span></label>

                    <input style="width:273px;" type="text" name="remarks" id="remarks" /></li>

        <li style="height: 15px; width: 100%"> </li>

                <li>

                <label for="ccno"><span id="lang_ccno">מס' כרטיס</span><span class="ast">*</span></label>

                <input type="text" name="ccno" id="ccno" autocomplete="off" /></li>

        <li>

                <label for="expmonth"><span id="lang_expiration">תוקף</span><span class="ast">*</span></label>

                <select name="expmonth" id="expmonth" style="width:50px;"><option value="01">1</option><option value="02">2</option><option value="03">3</option><option value="04">4</option><option value="05">5</option><option value="06">6</option><option value="07">7</option><option value="08">8</option><option value="09">9</option><option value="10">10</option><option value="11">11</option><option value="12">12</option></select>

                /

                <select name="expyear" id="expyear" style="width:75px;"><option value="14">2014</option><option value="15">2015</option><option value="16">2016</option><option value="17">2017</option><option value="18">2018</option><option value="19">2019</option><option value="20">2020</option><option value="21">2021</option><option value="22">2022</option><option value="23">2023</option><option value="24">2024</option><option value="25">2025</option><option value="26">2026</option><option value="27">2027</option><option value="28">2028</option><option value="29">2029</option><option value="30">2030</option></select></li>

        <li id="sumli"> </li>

        <li id="pmntid">

<label for="xnpay"><span id="lang_payments">מס תשלומים</span></label> <select id="xnpay" style="width: 138px;" name="xnpay" onchange="paymentscalc()"><option value="1">1</option><option value="2">2</option><option value="3">3</option></select><input type="hidden" name="npay" id="npay" value="" /><input type="hidden" name="fpay" id="fpay" value="" /><input type="hidden" name="spay" id="spay" value="" /><input type="hidden" name="tranmode" id="tranmode" value="" /><input type="hidden" name="cred_type" id="cred_type" value="" /></li>

        <li>

                                        <label for="myid"><span id="lang_id">ת.ז.</span><span class="ast">*</span></label>

                                        <input type="tel" name="myid" id="myid" /></li><li>

                        <label for="mycvv"><a href="#" onclick="window.open('/docs/window-cvv.html', '_blank', 'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=350,height=230, top=' + (parseInt((screen.availHeight/2) - 115)) + ',left='+(parseInt((screen.availWidth/2) - 175)));">CVV</a>:<span class="ast">*</span></label>

                        <input type="tel" name="mycvv" id="mycvv" style="width: 50px;" size="4" maxlength="4" /></li>

        <li><input type="hidden" name="currency" id="currency" value="1" /><input type="hidden" name="supplier" id="supplier" value="ttxbpracti" /><input type="hidden" name="sum" id="sum" value="" readonly="readonly" style="width: 105px" />  </li>

        <li class="checkoutb" style="display: block; float: left; margin-left: 70px; margin-top: 20px;">

        <span class="mysum"> <span id="lang_sum">סה"כ לתשלום</span> </span>  <span class="mysumval" id="sumval"></span><span class="mysumval" id="currchar"> ₪</span><br /><br /><span id="lang_paybycard">שלם באמצעות כרטיס אשראי</span> <button id="send" type="button" onclick="if(checknrun(required,'cc')) {this.disabled=true;this.form.submit();}">בצע תשלום</button>

        </li>

    </ul><input type="hidden" id="o_cred_type" name="o_cred_type" value="" /></form>

                                </div>

                                <div class="product">

                                        <div class="photo"></div>

                                </div>

                        </div>

                                <div id="gray">

                                        <div class="graystripe"> </div>

                                </div>

                                <div id="details">

                                        <div class="logom">

                                                <center><img src="merchant_logo.jpg" alt="Logo" /></center>

                                        </div>

                                        <p class="bizname">Bpracti סדנאות פרקטיקה</p>

                                        <ul><li class="biztext"><strong>כתובת:</strong> לאן 10/2</li>

                                        <li class="biztext"><strong style="visibility: hidden;">כתובת2</strong> רמת גן  </li>

                                        <li class="biztext"><strong>טלפון:</strong> 054-2099322</li>

                                        <li class="biztext"><strong>דוא"ל:</strong> <br /><a href="mailto:info@bpracti.co.il">info@bpracti.co.il</a></li>

                                        <li class="biztext"><strong>דף הבית :</strong> <br /><a href="http://www.bpracti.co.il" target="_blank">http://www.bpracti.co.il</a></li>

                                        </ul><div class="orangeright"><div class="pf"></div>

                                        </div>

                                        <div class="geo">

                        <table><tr><td><script type="text/javascript" src="//smarticon.geotrust.com/si.js"></script></td>

                            <td><img style="float:left;" width="146" height="51" border="0" src="/images/pci-inner.gif" alt="PCI DSS" /></td>

                        </tr></table></div>

                </div>

                </div>

                <div style="clear: both"></div>

                        <div id="footer">

                <div style="clear: both"></div>

                        <div id="footergreenstripe"></div>

                                <ul class="footergreenstripe"><li class="footertext"><span class="footerlink" onclick="trainto('http://www.bpracti.co.il/%D7%9E%D7%99-%D7%90%D7%A0%D7%97%D7%A0%D7%95/');">אודות</span></li>

                                        <li class="footertext"><span class="footerlink" onclick="trainto('http://www.bpracti.co.il/');">צור קשר</span></li>

                                        <li class="footertext" style="padding-right:360px;">Tranzila © טרנזילה שירותי   <a href="http://www.tranzila.com/" class="footertext" target="_blank">סליקה באינטרנט</a> - <a href="http://www.intervision.co.il/" class="footertext" target="_blank">מחשוב ענן</a> - כל הזכויות שמורות</li>

                                </ul></div>

<script type="text/javascript">

                required = ["ccno","expmonth","expyear","mycvv","myid","phone","email","contact"];

            </script><fieldset style="visibility: hidden"></fieldset></body></html>

    [response] => Array
        (
            [code] => 200
            [message] => OK
        )

    [cookies] => Array
        (
            [0] => WP_Http_Cookie Object
                (
                    [name] => PHPSESSID
                    [value] => muk15j6pephbnh4ghukv326237
                    [expires] =>
                    [path] => /
                    [domain] => direct.tranzila.com
                    [secure] =>
                )

        )

    [filename] =>
)

**Comment by zaus** [comment]
See my reply in WP forum https://wordpress.org/support/topic/redirect-to-payment-gateway-not-working-using-cf7-3rd-4?replies=2#post-7298438

> I just recently completed a redirect with CF7, it's a little weird but not too complicated.
> You basically need two hooks:
> 1. one to preprocess the mapped fields and turn them into your redirect url (and bypass the regular sending since you don't want to post to the service, just redirect) -- see #5 of https://github.com/zaus/forms-3rdparty-integration#hooks
> 2. one to attach that redirect url to the CF7 instance, which you can within the hook ..._remote_success using something like

		$addl = $form->prop('additional_settings');
		$addl .= "\non_sent_ok: \"(function(){ location = {$this->redirect}})();\"";

		$form->set_properties(array('additional_settings'=>$addl));

**Comment by zaus** [comment]
Closing -- not an issue with the plugin, and not something that I'd want to add to core.  Useful as an "add-on" plugin.
