### ISSUE TITLE
Question on Adding Filters

### ISSUE THREAD

**Issue by PthPndr** [zaus/forms-3rdparty-integration#46]
I ran across this plugin and it is exactly what we're looking for. I was able to setup the services with no issues but am having problems trying to setup a filter. I am not a developer so I am unsure about a lot of this.

We are using **Gravity Forms** and **MailChimp** to capture a user's birthday information. The Gravity Forms date format is **_mm/dd/yyyy_** and MailChimp wants **_mm/dd_**.

I ran across the code below which will do what I want but it is for the MailChimp's add-on for Gravity Forms. Is there a way to repurpose it for **forms-3rdparty-integration**?

```
		add_filter( 'gform_mailchimp_field_value', 'change_birthday', 10, 4 );
		function change_birthday( $value, $form_id, $field_id, $entry ) {
			//not the id for the birthday field, return value unchanged
			if ( $field_id != 4 ) {
				return $value;
			}

			$month = date( 'm', strtotime( $value ) ); //get month
			$day = date( 'd', strtotime( $value ) ); //get day
			$date = $month . '/' . $day; //build date into format needed by MailChimp
			return $date;       
		}
```

I can either submit **_mm/dd_** to MailChimp or I believe I can submit the **_mm_** and **_dd_** separately. Any help or point in the right direction would be greatly appreciated.

**Comment by zaus** [comment]
Just hook to [`...service_filter_post`](https://github.com/zaus/forms-3rdparty-integration/blob/master/forms-3rdparty-integration.php#L463) to alter mapped values:

``` php
class Forms3rdpartyDateFormatting {
	const B = 'Forms3rdPartyIntegration';
	
	private $_field; // where to look for the expected field
	
	function __construct() {
		// hook even later than xpost so we can manipulate final output
		add_filter(self::B.'service_filter_post', array(&$this, 'adjust_format'), 11, 5); // don't actually need all 5, just the $post
		
		$this->_field = 'your-date-field'; // or get from a configurable wp_option?
	}
	
	public function adjust_format($post, $service, $form, $sid, $submission) {
        $date = $post[$this->_field];
		
		// do your parsing + formatting
		
		$post[$this->_field] = $date;
		
		return $post;
    }
}
```
