### ISSUE TITLE
Trying to set up Contact Form 7 to integrate with Salesforce & Mailchimp

### ISSUE THREAD

**Issue by pmorettini** [zaus/forms-3rdparty-integration#5]
Hi,

I've just installed the plug-in and am very confused by the interface. Sorry, I'm sure it's my fault I'm a newbie.

I expected to see some type of template set up to work with these two services based upon the plugin description. But I don't see anything like that and really don't know how to start the integrations. Can someone be kind enough to point me in the right direction?

Thanks,

Phil

**Comment by hirewebsolutions** [comment]
Hello,

Contact Form 7 Salesforce CRM Integration: https://codecanyon.net/item/contact-form-7-salesforce-crm-integration/20100042

Thank You
