### ISSUE TITLE
ability to mix "label" and "form submission field" 

### ISSUE THREAD

**Issue by garubi** [zaus/forms-3rdparty-integration#51]
For enhanced mapping wolud be great if we could add (on specific fileds only) some "fixed text" to the value of a field.
This is very useful when posting to some "additional notes" fileds when you shold be able to provide some context to the information too...

I think the easiest way is to use the text already inserted as "Label" and not used anywhere... maybe with a placeholder in the "form submission field" where the text sholud be inserted.

See this mockup since my english is really bad ;-) 

![forms- 3rd party integration ufficio temporaneo wordpress 2015-12-02 18-09-05](https://cloud.githubusercontent.com/assets/10868669/11537943/d5c5655a-991f-11e5-92f3-1b265e0ec2fc.png)

**Comment by zaus** [comment]
Well, you can map multiple things to the same 3rd party field, and specify the separator character.  So if you map a static value with your "prefix" to 'extra' and the 'vat' form field to extra, it'll combine both just like you wanted.
