### ISSUE TITLE
problem to send data field. respond_message=no

### ISSUE THREAD

**Issue by omid516** [zaus/forms-3rdparty-integration#54]
# i try to login to panel.sedak.ir with username and password from gf.
creat new service and choose my form.
map the fields. but no respond!!
may you help me>?

`--- POST (array) ---
Array
(
)

--- POST (raw) ---

--- GET ---
Array
(
    [response_message] => no
    [id] => 29
)

--- META ---
Array
(
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => response_message=no&id=29
    [HTTP_HOST] => sedak.ir
    [HTTP_REFERER] => http://sedak.ir/%D8%A8%D8%B1%DA%AF%D9%87-%D9%86%D9%85%D9%88%D9%86%D9%87/
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
)

--- HEADERS ---
(getallheaders)
Array
(
    [Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    [Accept-Encoding] => gzip, deflate, sdch
    [Accept-Language] => en-US,en;q=0.8,fa;q=0.6
    [Connection] => keep-alive
    [Cookie] => wordpress_486466fafbd8ca99164aaa5e79b16df9=omid%7C1454499629%7C65vBwK3F4mmMkIHhPKa01pBrQII0UXCwnJDKIpVdBEH%7C27e4bdaf64fb68312ebc6b140abdfc3c1a2a5fdad338567282e1c144e86c2c15; wp-settings-1=editor%3Dhtml; wp-settings-time-1=1453905517; wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_486466fafbd8ca99164aaa5e79b16df9=omid%7C1454499629%7C65vBwK3F4mmMkIHhPKa01pBrQII0UXCwnJDKIpVdBEH%7C1e3c03bb728079256f919e2b189313c9827ebafaab14fcd9b9c57750fd3e2709; PHPSESSID=ed35e78cb9b80d51d32110dd8bbcd6d8; _wp_session=963045121a317af5510a5e8745750023%7C%7C1454333025%7C%7C1454332665
    [Host] => sedak.ir
    [Referer] => http://sedak.ir/%D8%A8%D8%B1%DA%AF%D9%87-%D9%86%D9%85%D9%88%D9%86%D9%87/
    [Upgrade-Insecure-Requests] => 1
    [User-Agent] => Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
)`

**Comment by zaus** [comment]
You forgot the most important part of the debug email -- what's your service setup?

**Comment by omid516** [comment]
**## it's full report: 
**
*** Service ***
Array
(
    [name] => s1
    [url] => http://panel.sedak.ir/login
    [forms] => Array
        (
            [0] => gf_1
        )

    [success] =>
    [failure] => no  %2$s
    [timeout] => 10
    [mapping] => Array
        (
            [0] => Array
                (
                    [lbl] => name
                    [src] => input_1_1
                    [3rd] => Username
                )

            [1] => Array
                (
                    [lbl] => pass
                    [src] => input_1_2
                    [3rd] => Password
                )

        )

    [separator] =>
)

*** Post (Form) ***
http://sedak.ir/1-2/
Array
(
    [input_1] => ee
    [input_2] => rr
    [gform_ajax] => form_id=1&title=1&description=1&tabindex=1
    [is_submit_1] => 1
    [gform_submit] => 1
    [gform_unique_id] =>
    [state_1] => WyJbXSIsImNiODY5NTJkNzUzM2FkYjFlOGEzOTE3MTRiZmUwZGY3Il0=
    [gform_target_page_number_1] => 0
    [gform_source_page_number_1] => 1
    [gform_field_values] =>
    [name] => ee
    [pass] => rr
)

*** Post (to Service) ***
Array
(
    [timeout] => 10
    [body] => Array
        (
        )

)

*** Response ***
Array
(
    [headers] => Array
        (
            [cache-control] => private
            [content-type] => text/html; charset=utf-8
            [server] => Microsoft-IIS/7.5
            [set-cookie] => Array
                (
                    [0] => ASP.NET_SessionId=ztyycmk1cekcggmvijuf32ir; path=/; HttpOnly
                    [1] => ASP.NET_SessionId=ztyycmk1cekcggmvijuf32ir; path=/; HttpOnly
                    [2] => __RequestVerificationToken=E6poexlVbzZ2Cy_UP3N5qJvDeGtYQrhiPpmDa_xmMaAkLt03NSJT2UyMgyYZJrjaykScyEVDK95074mUee0Yf6NiuN1sH2FgBHFWCerWgY6B3gwq1UaiT3B9JjKrD1j-NA4IOaW6RyygSuGG3NAZnQ2; path=/; HttpOnly
                )

            [x-aspnetmvc-version] => 4.0
            [x-aspnet-version] => 4.0.30319
            [x-powered-by] => ASP.NET
            [date] => Fri, 05 Feb 2016 07:34:28 GMT
            [connection] => close
            [content-length] => 2500
        )

    [body] =>

<!DOCTYPE html>




<html lang="en">

<head>
    <meta charset="utf-8">
    <title>ورود به سامانه</title>
    <link href="/Content/css/login.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <section id="content">
            <div style="text-align:center;">
                <img src="/client/settings/brand" style="border-radius:5px; max-width:100%;" />
            </div>
<form action="/login" method="post"><input name="__RequestVerificationToken" type="hidden" value="-HsSRohQhTHAOENGy23muOI0jRtXs2wC4xWmyrfvEWvTcgWgjMChtEuEz7OExobklMXFRpnKwtOCwLRJTc9JEoQvUQ0Y6mIvtPmA_8HeVOIPTfjHzzU3wFHZMgbkr5-5gnO4BYWmesAs2Df9V6C6WzZw6FEwoSAl2ErwoX0D5-01" />                <h1>ورود به سامانه</h1>
                <div>
                    <input class="input-validation-error" data-val="true" data-val-required="نام کاربری الزامیست" id="UserName" name="UserName" placeholder="نام کاربری" type="text" value="" />
                </div>
                <div>
                    <input class="input-validation-error" data-val="true" data-val-required="رمزعبور الزامیست" id="Password" name="Password" placeholder="رمزعبور" type="password" />
                </div>
                <div>
                    <input type="submit" value="ورود" />
                    <a href="/account/forget/">بازیابی رمزعبور</a>
                        <a href="/account/register/">ثبت نام</a>
                </div>
</form>            <div class="button">

                <div class="validation-summary-errors" data-valmsg-summary="true"><ul><li>نام کاربری الزامیست</li>
<li>رمزعبور الزامیست</li>
<li>نام کاربری وارد نشده است</li>
</ul></div>
            </div>
        </section>

    </div>
    <input type="hidden" id="id" value="12871" />
    <script src="/Content/js/jquery-2.0.3.min.js"></script>
    <script src="/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="/Scripts/jquery.validate.js"></script>
<script src="/Scripts/jquery.validate.unobtrusive.js"></script>

</body>
</html>
    [response] => Array
        (
            [code] => 200
            [message] => OK
        )

    [cookies] => Array
        (
            [0] => WP_Http_Cookie Object
                (
                    [name] => ASP.NET_SessionId
                    [value] => ztyycmk1cekcggmvijuf32ir
                    [expires] =>
                    [path] => /
                    [domain] => panel.sedak.ir
                    [httponly] =>
                )

            [1] => WP_Http_Cookie Object
                (
                    [name] => ASP.NET_SessionId
                    [value] => ztyycmk1cekcggmvijuf32ir
                    [expires] =>
                    [path] => /
                    [domain] => panel.sedak.ir
                    [httponly] =>
                )

            [2] => WP_Http_Cookie Object
                (
                    [name] => __RequestVerificationToken
                    [value] => E6poexlVbzZ2Cy_UP3N5qJvDeGtYQrhiPpmDa_xmMaAkLt03NSJT2UyMgyYZJrjaykScyEVDK95074mUee0Yf6NiuN1sH2FgBHFWCerWgY6B3gwq1UaiT3B9JjKrD1j-NA4IOaW6RyygSuGG3NAZnQ2
                    [expires] =>
                    [path] => /
                    [domain] => panel.sedak.ir
                    [httponly] =>
                )

        )

    [filename] =>
)


 i have account from panel.sedak.ir and i wanna login to it from my wordpress website.
thanks for your cool support

**Comment by omid516** [comment]
function login() {
var username = $('#username').val();
            var password = $('#password').val();
            $.ajax({
                url: 'http://portal.sedak.ir/account/ajaxlogin/',
                data: { username: username, password: password },
                type: 'POST',
                success: function (data) {
                    if (data.result) {
                        window.location = 'http://portal.sedak.ir/account/tokenlogin/?username=' + username + '&token=' + data.token;
                    }
                    else {
                        var error = '';
                        $.each(data.message, function (index, item) {
                            error += item + ',';
                        })
                        alert(error);
                    }
                }
            })
        
 } 

it's function for login to panel.sedak.ir with token

**Comment by zaus** [comment]
Oooh that's the first Unicode endpoint reply I've seen!  Cool!  Is that Farsi?

But I see your problem right there - you've mapped `input_1_1` etc but the form is posting `input_1` instead.  You may also note that is also posting `name` (and `pass`) which may be easier to map to.

**Comment by omid516** [comment]
# Yes Sir.
It's Farsi (Persian)
result with input_1:

*## it's full report: 
*
*** Service ***
Array
(
[name] => s1
[url] => http://panel.sedak.ir/login
[forms] => Array
(
[0] => gf_1
)

[success] =>
[failure] => no  %2$s
[timeout] => 10
[mapping] => Array
    (
        [0] => Array
            (
                [lbl] => name
                [src] => input_1
                [3rd] => Username
            )

        [1] => Array
            (
                [lbl] => pass
                [src] => input_2
                [3rd] => Password
            )

    )

[separator] =>
)

*** Post (Form) ***
http://sedak.ir/1-2/
Array
(
[input_1] => ee
[input_2] => rr
[gform_ajax] => form_id=1&title=1&description=1&tabindex=1
[is_submit_1] => 1
[gform_submit] => 1
[gform_unique_id] =>
[state_1] => WyJbXSIsImNiODY5NTJkNzUzM2FkYjFlOGEzOTE3MTRiZmUwZGY3Il0=
[gform_target_page_number_1] => 0
[gform_source_page_number_1] => 1
[gform_field_values] =>
[name] => ee
[pass] => rr
)

*** Post (to Service) ***
Array
(
[timeout] => 10
[body] => Array
(
)

)

*** Response ***
Array
(
[headers] => Array
(
[cache-control] => private
[content-type] => text/html; charset=utf-8
[server] => Microsoft-IIS/7.5
[set-cookie] => Array
(
[0] => ASP.NET_SessionId=ztyycmk1cekcggmvijuf32ir; path=/; HttpOnly
[1] => ASP.NET_SessionId=ztyycmk1cekcggmvijuf32ir; path=/; HttpOnly
[2] => __RequestVerificationToken=E6poexlVbzZ2Cy_UP3N5qJvDeGtYQrhiPpmDa_xmMaAkLt03NSJT2UyMgyYZJrjaykScyEVDK95074mUee0Yf6NiuN1sH2FgBHFWCerWgY6B3gwq1UaiT3B9JjKrD1j-NA4IOaW6RyygSuGG3NAZnQ2; path=/; HttpOnly
)

        [x-aspnetmvc-version] => 4.0
        [x-aspnet-version] => 4.0.30319
        [x-powered-by] => ASP.NET
        [date] => Fri, 05 Feb 2016 07:34:28 GMT
        [connection] => close
        [content-length] => 2500
    )

[body] =>
<!DOCTYPE html>



ورود به سامانه








ورود به سامانه










بازیابی رمزعبور
ثبت نام

            <div class="validation-summary-errors" data-valmsg-summary="true"><ul><li>نام کاربری الزامیست</li>
رمزعبور الزامیست

نام کاربری وارد نشده است




</div>
<input type="hidden" id="id" value="12871" />
<script src="/Content/js/jquery-2.0.3.min.js"></script>
<script src="/Scripts/jquery.unobtrusive-ajax.js"></script>


[response] => Array
(
[code] => 200
[message] => OK
)

[cookies] => Array
    (
        [0] => WP_Http_Cookie Object
            (
                [name] => ASP.NET_SessionId
                [value] => ztyycmk1cekcggmvijuf32ir
                [expires] =>
                [path] => /
                [domain] => panel.sedak.ir
                [httponly] =>
            )

        [1] => WP_Http_Cookie Object
            (
                [name] => ASP.NET_SessionId
                [value] => ztyycmk1cekcggmvijuf32ir
                [expires] =>
                [path] => /
                [domain] => panel.sedak.ir
                [httponly] =>
            )

        [2] => WP_Http_Cookie Object
            (
                [name] => __RequestVerificationToken
                [value] => E6poexlVbzZ2Cy_UP3N5qJvDeGtYQrhiPpmDa_xmMaAkLt03NSJT2UyMgyYZJrjaykScyEVDK95074mUee0Yf6NiuN1sH2FgBHFWCerWgY6B3gwq1UaiT3B9JjKrD1j-NA4IOaW6RyygSuGG3NAZnQ2
                [expires] =>
                [path] => /
                [domain] => panel.sedak.ir
                [httponly] =>
            )

    )

[filename] =>


**# _tnx for your answers..._**

**Comment by zaus** [comment]
Weird, that should have a submission body.  What plugin version are you using? Do you have any other plugins installed? Can you try posting to the debug endpoint instead of sendak.ir?

**Comment by omid516** [comment]
**it's Forms: 3rd-Party Integration 1.6.6.3
**
*** Service ***
Array
(
    [name] => s1
    [url] => http://sedak.ir/wp-content/plugins/forms-3rdparty-integration/3rd-parties/service_test.php
    [forms] => Array
        (
            [0] => gf_1
        )

    [success] =>
    [failure] => no  %2$s
    [timeout] => 10
    [mapping] => Array
        (
            [0] => Array
                (
                    [lbl] => name
                    [src] => input_1
                    [3rd] => Username
                )

            [1] => Array
                (
                    [lbl] => pass
                    [src] => input_2
                    [3rd] => Password
                )

        )

    [separator] =>
)

*** Post (Form) ***
http://sedak.ir/1-2/
Array
(
    [input_1] => testttt
    [input_2] => 222testttt
    [gform_ajax] => form_id=1&title=1&description=1&tabindex=1
    [is_submit_1] => 1
    [gform_submit] => 1
    [gform_unique_id] =>
    [state_1] => WyJbXSIsImNiODY5NTJkNzUzM2FkYjFlOGEzOTE3MTRiZmUwZGY3Il0=
    [gform_target_page_number_1] => 0
    [gform_source_page_number_1] => 1
    [gform_field_values] =>
    [name] => testttt
    [pass] => 222testttt
)

*** Post (to Service) ***
Array
(
    [timeout] => 10
    [body] => Array
        (
            [Username] => testttt
            [Password] => 222testttt
        )

)

*** Response ***
Array
(
    [headers] => Array
        (
            [date] => Sat, 06 Feb 2016 19:18:20 GMT
            [server] => Apache
            [x-powered-by] => PHP/5.4.45
            [connection] => close
            [content-type] => text/plain
        )

    [body] => --- POST (array) ---
Array
(
    [Username] => testttt
    [Password] => 222testttt
)

--- POST (raw) ---
Username=testttt&Password=222testttt
--- GET ---
Array
(
)

--- META ---
Array
(
    [REQUEST_METHOD] => POST
    [QUERY_STRING] =>
    [HTTP_HOST] => sedak.ir
    [HTTP_REFERER] =>
    [HTTP_USER_AGENT] => WordPress/4.3.3; http://sedak.ir
)

--- HEADERS ---
(getallheaders)
Array
(
    [Content-Length] => 36
    [Content-Type] => application/x-www-form-urlencoded; charset=UTF-8
    [Accept] => */*
    [Accept-Encoding] => deflate;q=1.0, compress;q=0.5, gzip;q=0.5
    [Host] => sedak.ir
    [User-Agent] => WordPress/4.3.3; http://sedak.ir
)

    [response] => Array
        (
            [code] => 200
            [message] => OK
        )

    [cookies] => Array
        (
        )

    [filename] =>
)


my plugins:
Azul - Creative Coming Soon Template
Gravity Forms
oAuth Twitter Feed for Developers
Revolution Slider
Simple Custom Post Order
WordPress Importer

**Comment by zaus** [comment]
Well, that had a submission body.  No idea why sending to another endpoint url would not.
You might need to add some debugging within the plugin to see what's in the `post_args` right before they're sent, because they should be there.  Did you write any custom hooks?

**Comment by omid516** [comment]
no...
i never write any custom hooks

**Comment by zaus** [comment]
Closing without resolution, inactivity
