### ISSUE TITLE
JavaScript Integration, action to before submit to url

### ISSUE THREAD

**Issue by ravikumarmurai** [zaus/forms-3rdparty-integration#58]
Hi,

I want to submit a form to my wp database as well as external service, but some of fields should taken by using jquery or javascript

**Comment by zaus** [comment]
You mean you want the form to include extra values determined by javascript?  My plugin will pick up whatever the original form plugin provides (usually any `$_POST` variables are available).

I think you want something that extends the functionality of Gravity Forms or CF7 to do what you want; once it's being submitted with the form then you can map it with my plugin.

**Comment by zaus** [comment]
Not relevant to plugin, closing.
