### ISSUE TITLE
Web service integration

### ISSUE THREAD

**Issue by digaworks** [zaus/forms-3rdparty-integration#61]
Hi,

How would I integrate with a web service to send form submissions. The web service URL is "http://URL.asmx?WSDL" and the action to add this submission to the web service is "AddLead". I'm getting an error when I enter the web service URL into the settings. And I'm not sure where to enter in the "AddLead" action.

Thanks!

**Comment by zaus** [comment]
You'll need the XPost addon https://github.com/zaus/forms-3rdparty-xpost as mentioned on the FAQ page for _this_ plugin and probably need to set a `SOAPAction` header.

You could also write a custom 'bypass' hook and make the SOAP request yourself following instructions like http://wpquestions.com/question/showChrono/id/7317

Closing as not directly an issue with the plugin.  Feel free to continue the thread.
