### ISSUE TITLE
API

### ISSUE THREAD

**Issue by kodeine** [zaus/forms-3rdparty-integration#62]
Hello,
Is it possible to get if service is being used for a form by ```GFAPI::get_entry($entry_id)``` maybe we can store the attached services in meta this way its easier to re-run the 3rd-party call dynamically.

For example, im using gravityview for form edits. But edits/deletions should run service again so 3rd party knows there's an update or deletion to the entry.

If there's a better way to handle this please let me know.

Also, how can i actually re-run the service?

Thanks

**Comment by zaus** [comment]
Someone asked this question on the WP forums (you, probably?).

The important part is to attach my plugin's functionality to a "form", similar to how Gravity Forms is already attached: https://github.com/zaus/forms-3rdparty-integration/blob/master/plugins/gravityforms.php

You can write a class extending `Forms3rdpartyIntegration_FPLUGIN` similar to the above, but declaring the GF edit hook via `BEFORE_SEND_FILTER`.

I could make this a little easier by [allowing an array](https://github.com/zaus/forms-3rdparty-integration/blob/master/plugins/fplugin_base.php#L122) and adding some plugin-specific filters just in case the `$form` differs.

**Comment by zaus** [comment]
working on it...
