### ISSUE TITLE
Wordpress 4.4.2 

### ISSUE THREAD

**Issue by cmatta24** [zaus/forms-3rdparty-integration#63]
Any timeline when it will be compatible with Wordpress 4.4.2?

**Comment by systatsoftware** [comment]
WP 4.5 is now out.

Is it safe to update to 4.5?

**Comment by zaus** [comment]
Should be fine.  There shouldn't be anything intrinsically incompatible with Wordpress, as all of the hooks are based on other contact form plugins.

Please let me know if it _doesn't_ work and I'll reopen the ticket.
