### ISSUE TITLE
Debug emails not sent

### ISSUE THREAD

**Issue by redanina** [zaus/forms-3rdparty-integration#66]
Hi, I cannot get the debug emails to be sent. I've attached the 3rd party integration to a CF& form but simply nothing happens when I launch the form. Any idea?

**Comment by zaus** [comment]
You'll have to provide way more details.  What version of WordPress?  Php? What other plugins do you have installed? Does CF7 successfully submit and send an email?  What mapping/configuration are you using?  Can you turn on wp_debug mode and logging? Etc...
