### ISSUE TITLE
Velocify

### ISSUE THREAD

**Issue by RYANCHANEL** [zaus/forms-3rdparty-integration#72]
I've been working with Velocify customer service. They are insisting no data is coming over. The debug emails I get say otherwise. Hopefully I'm missing something simple? Please see debug below and note the URL was changed due to my company using URL defense. Thank you for your help! Dummy contact info was used so I didn't change any of it:
*** Service ***
Array
(
    [name] => Velocify
    [url] => https://urldefense.proofpoint.com/v2/url?u=https-3A__secure.velocify.com_Import.aspx-3FProvider-3DBrenkus-26Client-3D31146-26CampaignId-3D22&d=DQIDaQ&c=2edShaNLCCxkvl73OatCmb97tzWob_MYTzXL7guj3gs&r=MihH_NXb3yd3aVqOjojzeyBW9CeQJSTPpgRi7zB9Ygc&m=pHkGla2zycdTFN3_7-2WLHl2d7PXnTXXyrTkPB_yQ_c&s=AAgu1uRGYzf71o7AR3EHoISyZ-XhsQ4HBjSF22902rM&e= 
    [forms] => Array
        (
            [0] => gf_1
        )

    [success] => 
    [failure] => 
    [timeout] => 10
    [dynamic-attach] => yes
    [dynamic-format] => %s = %s;
    [mapping] => Array
        (
            [1] => Array
                (
                    [lbl] => Client First Name
                    [src] => Field ID 1
                    [3rd] => First Name
                )

            [2] => Array
                (
                    [lbl] => Client Last Name
                    [src] => Field ID 2
                    [3rd] => Last Name
                )

            [3] => Array
                (
                    [lbl] => Client Email
                    [src] => Field ID 3
                    [3rd] => Email
                )

            [4] => Array
                (
                    [lbl] => Client Phone
                    [src] => Field ID 4
                    [3rd] => H. Phone
                )

            [5] => Array
                (
                    [lbl] => Note
                    [src] => Field ID 5
                    [3rd] => Incoming Note
                )

            [6] => Array
                (
                    [lbl] => Agent First Name
                    [src] => Field ID 7
                    [3rd] => Borrower's Agent: First Name
                )

            [7] => Array
                (
                    [lbl] => Agent Last Name
                    [src] => Field ID 8
                    [3rd] => Borrower's Agent: Last Name
                )

            [8] => Array
                (
                    [lbl] => Agent Company
                    [src] => Field ID 9
                    [3rd] => Borrower's Agent: Company Name
                )

            [9] => Array
                (
                    [lbl] => Agent Email
                    [src] => Field ID 12
                    [3rd] => Borrower's Agent: Email Address
                )

            [10] => Array
                (
                    [lbl] => Agent Phone
                    [src] => Field ID 11
                    [3rd] => Borrower's Agent: Phone
                )

        )

    [separator] => , 
)

*** Post (Form) ***
https://urldefense.proofpoint.com/v2/url?u=http-3A__srmforms.com_brenkus&d=DQIDaQ&c=2edShaNLCCxkvl73OatCmb97tzWob_MYTzXL7guj3gs&r=MihH_NXb3yd3aVqOjojzeyBW9CeQJSTPpgRi7zB9Ygc&m=pHkGla2zycdTFN3_7-2WLHl2d7PXnTXXyrTkPB_yQ_c&s=_28AcyMC8luhx43KkNvAOJnnayoFh5nPmOJf1_yGpAU&e= 
Array
(
    [input_1] => Ryan
    [input_2] => Adams
    [input_3] => adams.ryan.c@gmail.com
    [input_4] => 7205262797
    [input_5] => Test
    [input_7] => Ryan
    [input_8] => Adams
    [input_9] => 
    [input_12] => adams.ryan.c@gmail.com
    [input_11] => 
    [is_submit_1] => 1
    [gform_submit] => 1
    [gform_unique_id] => 
    [state_1] => WyJbXSIsIjNmN2IzYzhjZTlmZDg4OTMyZjM0YmJhZTViOTM3NTYwIl0=
    [gform_target_page_number_1] => 0
    [gform_source_page_number_1] => 1
    [gform_field_values] => 
    [First Name] => Array
        (
            [0] => Ryan
            [1] => Ryan
        )

    [Last Name] => Array
        (
            [0] => Adams
            [1] => Adams
        )

    [Email] => Array
        (
            [0] => adams.ryan.c@gmail.com
            [1] => adams.ryan.c@gmail.com
        )

    [Phone] => 7205262797
    [Comments] => Test
    [Company/Team] => 
    [Cell] => 
)

*** Post (to Service) ***
Array
(
    [timeout] => 10
    [body] => Array
        (
        )

)

*** Response ***
Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [cache-control] => private
                    [content-type] => text/html; charset=utf-8
                    [server] => Microsoft-IIS/7.5
                    [set-cookie] => ASP.NET_SessionId=k3wa404sb5iywzjmlpn2ydwj; path=/; HttpOnly
                    [x-powered-by] => ASP.NET
                    [date] => Wed, 21 Sep 2016 23:02:27 GMT
                    [content-length] => 8
                )

        )

    [body] => Failure 
    [response] => Array
        (
            [code] => 200
            [message] => OK
        )

    [cookies] => Array
        (
            [0] => WP_Http_Cookie Object
                (
                    [name] => ASP.NET_SessionId
                    [value] => k3wa404sb5iywzjmlpn2ydwj
                    [expires] => 
                    [path] => /
                    [domain] => secure.velocify.com
                )

        )

    [filename] => 
    [http_response] => WP_HTTP_Requests_Response Object
        (
            [response:protected] => Requests_Response Object
                (
                    [body] => Failure 
                    [raw] => HTTP/1.1 200 OK
Cache-Control: private
Content-Type: text/html; charset=utf-8
Server: Microsoft-IIS/7.5
Set-Cookie: ASP.NET_SessionId=k3wa404sb5iywzjmlpn2ydwj; path=/; HttpOnly
X-Powered-By: ASP.NET
Date: Wed, 21 Sep 2016 23:02:27 GMT
Connection: close
Content-Length: 8

Failure 
                    [headers] => Requests_Response_Headers Object
                        (
                            [data:protected] => Array
                                (
                                    [cache-control] => Array
                                        (
                                            [0] => private
                                        )

                                    [content-type] => Array
                                        (
                                            [0] => text/html; charset=utf-8
                                        )

                                    [server] => Array
                                        (
                                            [0] => Microsoft-IIS/7.5
                                        )

                                    [set-cookie] => Array
                                        (
                                            [0] => ASP.NET_SessionId=k3wa404sb5iywzjmlpn2ydwj; path=/; HttpOnly
                                        )

                                    [x-powered-by] => Array
                                        (
                                            [0] => ASP.NET
                                        )

                                    [date] => Array
                                        (
                                            [0] => Wed, 21 Sep 2016 23:02:27 GMT
                                        )

                                    [content-length] => Array
                                        (
                                            [0] => 8
                                        )

                                )

                        )

                    [status_code] => 200
                    [protocol_version] => 1.1
                    [success] => 1
                    [redirects] => 0
                    [url] => https://urldefense.proofpoint.com/v2/url?u=https-3A__secure.velocify.com_Import.aspx-3FProvider-3DBrenkus-26Client-3D31146-26CampaignId-3D22&d=DQIDaQ&c=2edShaNLCCxkvl73OatCmb97tzWob_MYTzXL7guj3gs&r=MihH_NXb3yd3aVqOjojzeyBW9CeQJSTPpgRi7zB9Ygc&m=pHkGla2zycdTFN3_7-2WLHl2d7PXnTXXyrTkPB_yQ_c&s=AAgu1uRGYzf71o7AR3EHoISyZ-XhsQ4HBjSF22902rM&e= 
                    [history] => Array
                        (
                        )

                    [cookies] => Requests_Cookie_Jar Object
                        (
                            [cookies:protected] => Array
                                (
                                    [ASP.NET_SessionId] => Requests_Cookie Object
                                        (
                                            [name] => ASP.NET_SessionId
                                            [value] => k3wa404sb5iywzjmlpn2ydwj
                                            [attributes] => Requests_Utility_CaseInsensitiveDictionary Object
                                                (
                                                    [data:protected] => Array
                                                        (
                                                            [path] => /
                                                            [httponly] => 1
                                                            [domain] => secure.velocify.com
                                                        )

                                                )

                                            [flags] => Array
                                                (
                                                    [creation] => 1474498947
                                                    [last-access] => 1474498947
                                                    [persistent] => 
                                                    [host-only] => 1
                                                )

                                            [reference_time] => 1474498947
                                        )

                                )

                        )

                )

            [filename:protected] => 
            [data] => 
            [headers] => 
            [status] => 
        )

)

**Comment by RYANCHANEL** [comment]
Following up on this to see if you can provide assistance. I've been trying to get Velocify to help as well. Their latest feedback: Adjust the Posting String so it reads:
Field ID 1=Joe&Field ID 2=Doe&Field ID 3=Joe.Doe@mail.com&......

If it matters, the absolute latest debugging email is:

*** Service ***
Array
(
    [name] => Velocify
    [url] => https://urldefense.proofpoint.com/v2/url?u=https-3A__secure.velocify.com_Import.aspx-3FProvider-3DBrenkus-26Client-3D31146-26CampaignId-3D22&d=DQIDaQ&c=2edShaNLCCxkvl73OatCmb97tzWob_MYTzXL7guj3gs&r=MihH_NXb3yd3aVqOjojzeyBW9CeQJSTPpgRi7zB9Ygc&m=Z5FbBcFwhgYQqRI7FvqnbQsjKiEf-nYzkK9HAuZW_z0&s=xFGh2wPQk3CtAhtj8FYDTNpp1f6n1d7abIhHv5EO2xs&e= 
    [forms] => Array
        (
            [0] => gf_1
        )

    [success] => 
    [failure] => 
    [timeout] => 10
    [as-xpost] => true
    [xpost-wrapper] => post
    [xpost-header] => 
    [dynamic-attach] => yes
    [dynamic-format] => %s = %s;
    [mapping] => Array
        (
            [0] => Array
                (
                    [val] => 1
                    [lbl] => refid
                    [src] => **refid**
                    [3rd] => refid
                )

            [1] => Array
                (
                    [lbl] => Client First Name
                    [src] => Field ID 1
                    [3rd] => First Name
                )

            [2] => Array
                (
                    [lbl] => Client Last Name
                    [src] => Field ID 2
                    [3rd] => Last Name
                )

            [3] => Array
                (
                    [lbl] => Client Email
                    [src] => Field ID 3
                    [3rd] => Email
                )

            [4] => Array
                (
                    [lbl] => Client Phone
                    [src] => Field ID 4
                    [3rd] => H. Phone
                )

            [5] => Array
                (
                    [lbl] => Note
                    [src] => Field ID 5
                    [3rd] => Incoming Note
                )

            [6] => Array
                (
                    [lbl] => Agent First Name
                    [src] => Field ID 7
                    [3rd] => Borrower's Agent: First Name
                )

            [7] => Array
                (
                    [lbl] => Agent Last Name
                    [src] => Field ID 8
                    [3rd] => Borrower's Agent: Last Name
                )

            [8] => Array
                (
                    [lbl] => Agent Email
                    [src] => Field ID 12
                    [3rd] => Borrower's Agent: Email Address
                )

            [9] => Array
                (
                    [lbl] => Agent Phone
                    [src] => Field ID 11
                    [3rd] => Borrower's Agent: Phone
                )

        )

    [separator] => , 
)

*** Post (Form) ***
https://urldefense.proofpoint.com/v2/url?u=http-3A__srmforms.com_brenkus&d=DQIDaQ&c=2edShaNLCCxkvl73OatCmb97tzWob_MYTzXL7guj3gs&r=MihH_NXb3yd3aVqOjojzeyBW9CeQJSTPpgRi7zB9Ygc&m=Z5FbBcFwhgYQqRI7FvqnbQsjKiEf-nYzkK9HAuZW_z0&s=nr8JtyEdjBJaCfFML1uUGfj5it-XLpMXwDZ-juOIWF8&e= 
Array
(
    [input_1] => Ryan
    [input_2] => Adams
    [input_3] => adams.ryan.c@gmail.com
    [input_4] => 7205262797
    [input_5] => Test
    [input_7] => Ryan
    [input_8] => Adams
    [input_12] => adams.ryan.c@gmail.com
    [input_11] => 333-333-3333
    [is_submit_1] => 1
    [gform_submit] => 1
    [gform_unique_id] => 
    [state_1] => WyJbXSIsIjNmN2IzYzhjZTlmZDg4OTMyZjM0YmJhZTViOTM3NTYwIl0=
    [gform_target_page_number_1] => 0
    [gform_source_page_number_1] => 1
    [gform_field_values] => 
    [First Name] => Array
        (
            [0] => Ryan
            [1] => Ryan
        )

    [Last Name] => Array
        (
            [0] => Adams
            [1] => Adams
        )

    [Email] => Array
        (
            [0] => adams.ryan.c@gmail.com
            [1] => adams.ryan.c@gmail.com
        )

    [Phone] => 7205262797
    [Comments] => Test
    [Cell] => 333-333-3333
)

*** Post (to Service) ***
Array
(
    [timeout] => 10
    [body] => Array
        (
            [refid] => **refid**
        )

)

*** Response ***
Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [cache-control] => private
                    [content-type] => text/html; charset=utf-8
                    [server] => Microsoft-IIS/7.5
                    [set-cookie] => ASP.NET_SessionId=u1zkaavmcgz5n2gnouf3zfvk; path=/; HttpOnly
                    [x-powered-by] => ASP.NET
                    [date] => Thu, 22 Sep 2016 21:00:10 GMT
                    [content-length] => 8
                )

        )

    [body] => Success 
    [response] => Array
        (
            [code] => 200
            [message] => OK
        )

    [cookies] => Array
        (
            [0] => WP_Http_Cookie Object
                (
                    [name] => ASP.NET_SessionId
                    [value] => u1zkaavmcgz5n2gnouf3zfvk
                    [expires] => 
                    [path] => /
                    [domain] => secure.velocify.com
                )

        )

    [filename] => 
    [http_response] => WP_HTTP_Requests_Response Object
        (
            [response:protected] => Requests_Response Object
                (
                    [body] => Success 
                    [raw] => HTTP/1.1 200 OK
Cache-Control: private
Content-Type: text/html; charset=utf-8
Server: Microsoft-IIS/7.5
Set-Cookie: ASP.NET_SessionId=u1zkaavmcgz5n2gnouf3zfvk; path=/; HttpOnly
X-Powered-By: ASP.NET
Date: Thu, 22 Sep 2016 21:00:10 GMT
Connection: close
Content-Length: 8

Success 
                    [headers] => Requests_Response_Headers Object
                        (
                            [data:protected] => Array
                                (
                                    [cache-control] => Array
                                        (
                                            [0] => private
                                        )

                                    [content-type] => Array
                                        (
                                            [0] => text/html; charset=utf-8
                                        )

                                    [server] => Array
                                        (
                                            [0] => Microsoft-IIS/7.5
                                        )

                                    [set-cookie] => Array
                                        (
                                            [0] => ASP.NET_SessionId=u1zkaavmcgz5n2gnouf3zfvk; path=/; HttpOnly
                                        )

                                    [x-powered-by] => Array
                                        (
                                            [0] => ASP.NET
                                        )

                                    [date] => Array
                                        (
                                            [0] => Thu, 22 Sep 2016 21:00:10 GMT
                                        )

                                    [content-length] => Array
                                        (
                                            [0] => 8
                                        )

                                )

                        )

                    [status_code] => 200
                    [protocol_version] => 1.1
                    [success] => 1
                    [redirects] => 0
                    [url] => https://urldefense.proofpoint.com/v2/url?u=https-3A__secure.velocify.com_Import.aspx-3FProvider-3DBrenkus-26Client-3D31146-26CampaignId-3D22&d=DQIDaQ&c=2edShaNLCCxkvl73OatCmb97tzWob_MYTzXL7guj3gs&r=MihH_NXb3yd3aVqOjojzeyBW9CeQJSTPpgRi7zB9Ygc&m=Z5FbBcFwhgYQqRI7FvqnbQsjKiEf-nYzkK9HAuZW_z0&s=xFGh2wPQk3CtAhtj8FYDTNpp1f6n1d7abIhHv5EO2xs&e= 
                    [history] => Array
                        (
                        )

                    [cookies] => Requests_Cookie_Jar Object
                        (
                            [cookies:protected] => Array
                                (
                                    [ASP.NET_SessionId] => Requests_Cookie Object
                                        (
                                            [name] => ASP.NET_SessionId
                                            [value] => u1zkaavmcgz5n2gnouf3zfvk
                                            [attributes] => Requests_Utility_CaseInsensitiveDictionary Object
                                                (
                                                    [data:protected] => Array
                                                        (
                                                            [path] => /
                                                            [httponly] => 1
                                                            [domain] => secure.velocify.com
                                                        )

                                                )

                                            [flags] => Array
                                                (
                                                    [creation] => 1474578010
                                                    [last-access] => 1474578010
                                                    [persistent] => 
                                                    [host-only] => 1
                                                )

                                            [reference_time] => 1474578010
                                        )

                                )

                        )

                )

            [filename:protected] => 
            [data] => 
            [headers] => 
            [status] => 
        )

)

**Comment by zaus** [comment]
Please read https://wordpress.org/support/topic/its-not-sending-data-help-read-this-first/

Velocify customer service is correct -- you aren't sending any data:

> `*** Post (to Service) ***
Array
(
[timeout] => 10
[body] => Array
(
)
)`

and 

> `*** Post (to Service) ***
Array
(
[timeout] => 10
[body] => Array
(
[refid] => refid
)
)`

This is because you're not mapping the submission correctly.  Again, please read the sticky forum post.
