### ISSUE TITLE
Error 28: Operation timed out

### ISSUE THREAD

**Issue by AlexRogersWAD** [zaus/forms-3rdparty-integration#75]
Hello,

We have received the same error a few times over the last couple days and I'm looking for a way to fix it. Someone else set up the integration so I'm not very well versed in how this plugin works with connecting to the CRM. Please see the error email we received below:

There was an error when trying to integrate with the 3rd party service {ER Outtake} 

**SUBMISSION**
Array
(
   [timeout] => 20
   [body] => Array
       (
           [email] => rachelpete1223@gmail.com
           [phone] => (435) 790-7057
           [message] => 
           [first_name] => Rachel
           [last_name] => Peterson
           [more_info] => Culinary School
       )

)

**RAW RESPONSE**
Array
(
   [safe_message] => error object
   [object] => WP_Error Object
       (
           [errors] => Array
               (
                   [http_request_failed] => Array
                       (
                           [0] => cURL error 28: Operation timed out after 20001 milliseconds with 0 bytes received
                       )

               )

           [error_data] => Array
               (
               )

       )

)

**Comment by zaus** [comment]
It sounds like a "problem" with your CRM service taking too long; there is a setting to increase the "Request timeout" which presumably the person setting up the integration already changed to 20 (it defaults to 10); you might try increasing it, but you should contact your CRM rep to investigate why the API is so slow.
