### ISSUE TITLE
Not compatible with WP 4.9.1 ?

### ISSUE THREAD

**Issue by webx2** [zaus/forms-3rdparty-integration#95]
Hi,

I upgrade WP to 4.9.1. 
I use Contact Form 7 4.9.2 and your Plugin 3rdparty-integration 1.7.4

Its not sending data anymore.

No errors on the front-end

Any ideas to solve this problem?

Thanks in advance.

**Comment by zaus** [comment]
Sorry, it's been working just fine for me on that and newer versions.  You'll have to try turning on `WP_DEBUG` mode to investigate.
